site_name: Deep Learning in Weather
site_url: https://weatherml.github.io/
repo_url: https://github.com/weatherml/weatherml.github.io
repo_name: weatherml/weatherml.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: blue
    accent: cyan
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue
    accent: cyan
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
  - content.code.copy
  - content.tabs.link
  - navigation.indexes
  - navigation.top
  - navigation.tabs
  - navigation.instant
  - navigation.instant.prefetch
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Papers: papers.md
  - Tags: tags.md